# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - camel_case_types
    - cancel_subscriptions
    - test_types_in_equals
    - iterable_contains_unrelated_type

analyzer:
  exclude:
    - lib/paperplane.dart
    - lib/paperplane_exceptions.dart
    - lib/types.dart
#    - path/to/excluded/files/**
