name: paperplane
description: A Flying Telegram Bot API Wrapper created from Scratch and Paper.
version: 0.2.2
homepage: https://github.com/Nebulino/PaperPlane
issues: https://github.com/Nebulino/PaperPlane/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  path: ^1.6.4
  matcher: ^0.12.6

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  mockito: ^4.1.1
  json_serializable: ^3.2.5
  build_runner: ^1.8.0
