name: paperplane
description: A Flying Telegram Bot API Wrapper created from Scratch and Paper.
version: 0.6.1
homepage: https://github.com/Nebulino/PaperPlane
issues: https://github.com/Nebulino/PaperPlane/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  json_annotation: ^3.0.1
  logger: ^0.8.3
  dio: ^3.0.9
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  mockito: ^4.1.1
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
  matcher: ^0.12.6
